# Generated by Django 3.2.3 on 2021-08-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mission_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countyexpert',
            name='county',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expert', to='core.county'),
        ),
        migrations.AlterField(
            model_name='region',
            name='super_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_regions', to='core.region'),
        ),
    ]
