# Generated by Django 3.2.3 on 2021-05-29 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210529_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymoderator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='countyexpert',
            name='county',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.county'),
        ),
        migrations.AlterField(
            model_name='countyexpert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='countymoderator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('RP', 'Reported'), ('RJ', 'Rejected'), ('AC', 'Accepted'), ('FL', 'Failed'), ('AS', 'Assigned'), ('DO', 'Done'), ('SC', 'Scored')], default='RP', max_length=2),
        ),
        migrations.AlterField(
            model_name='provincemoderator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceman',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.serviceteam'),
        ),
        migrations.AlterField(
            model_name='serviceman',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
