# Generated by Django 3.2.3 on 2021-09-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210828_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinerytype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceman',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.serviceteam'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
