# Generated by Django 3.2.3 on 2021-05-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_citizen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.issue'),
        ),
    ]
