# Generated by Django 3.2.3 on 2021-09-04 08:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210903_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue-images/', validators=[core.models.Issue.validate_image]),
        ),
    ]
