# Generated by Django 3.2.3 on 2021-05-31 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mission_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceteam',
            name='active_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mission'),
        ),
        migrations.AlterField(
            model_name='serviceteam',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
