# Generated by Django 3.2.3 on 2021-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210531_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='type',
            field=models.CharField(choices=[('CR', 'Country'), ('PR', 'Province'), ('CY', 'County')], default='CRً', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='type',
            field=models.CharField(choices=[('CR', 'Country'), ('PR', 'Province'), ('CY', 'County')], default='CY', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='type',
            field=models.CharField(choices=[('CR', 'Country'), ('PR', 'Province'), ('CY', 'County')], default='PR', max_length=2),
            preserve_default=False,
        ),
    ]
