# Generated by Django 3.2.3 on 2021-05-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('SP', 'Simple'), ('CZ', 'Citizen'), ('SM', 'Serviceman'), ('PR', 'Country Moderator'), ('PM', 'Province Moderator'), ('CM', 'County Moderator'), ('CE', 'County Expert')], default='SP', max_length=2),
        ),
    ]
