name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      DEBUG=on
      SECRET_KEY=deKNY8GpQ6Y19nf78XNjGVbb6v6Af3y6
      DATABASE_URL=sqlite:////tmp/my-tmp-sqlite.db
      ALLOWED_HOSTS=*
      TIME_ZONE=Asia/Tehran
      DOMAIN=
      KAVENEGAR_API_KEY=
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r roadservice/requirements/development.txt
      
    - name: Migrate & Run Tests
      run: |
        python roadservice/manage.py migrate
        python roadservice/manage.py test
